# Generated by Django 4.2.1 on 2023-08-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZoomApp', '0004_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
